---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	impact_extraction(impact_extraction)
	impact_text(impact_text)
	impact_image(impact_image)
	impact_merge(impact_merge)
	thermal_extraction(thermal_extraction)
	thermal_text(thermal_text)
	thermal_image(thermal_image)
	thermal_merge(thermal_merge)
	reasoning_agent(reasoning_agent)
	save(save)
	__end__([<p>__end__</p>]):::last
	__start__ --> impact_extraction;
	__start__ --> thermal_extraction;
	impact_extraction --> impact_image;
	impact_extraction --> impact_text;
	impact_image --> impact_merge;
	impact_merge --> reasoning_agent;
	impact_text --> impact_merge;
	reasoning_agent --> save;
	thermal_extraction --> thermal_image;
	thermal_extraction --> thermal_text;
	thermal_image --> thermal_merge;
	thermal_merge --> reasoning_agent;
	thermal_text --> thermal_merge;
	save --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
